import {useState} from 'react';
import {Bone,RotateCcw,Search,Check,Eye,Target,ChevronRight,BookOpen} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import Viewer,{ViewName} from './viewer';
import {Scope,Side,catalog,defaultAnnotations,inScope,scopeLabels,pointSide,pointInSide,referenceUrl} from '@/lib/atlas';
const annotations=defaultAnnotations;
const course=catalog.filter(e=>e.kind==='bone'||annotations[e.id]?.reviewed);
export default function App(){
 const [region,setRegion]=useState<Scope>('all'),[side,setSide]=useState<Side>('both'),[selectedId,setSelectedId]=useState('humerus'),[practice,setPractice]=useState(false),[query,setQuery]=useState(''),[isolate,setIsolate]=useState(false),[showMarkers,setShowMarkers]=useState(false),[revealed,setRevealed]=useState(false),[notice,setNotice]=useState(''),[view,setView]=useState<{name:ViewName;sequence:number}>({name:'anterior',sequence:0});
 const selected=course.find(e=>e.id===selectedId)!,annotation=annotations[selectedId],entries=course.filter(e=>inScope(e,region)),landmarks=entries.filter(e=>e.kind==='landmark'),hidden=practice&&!revealed;
 function camera(name:ViewName){setView(v=>({name,sequence:v.sequence+1}));}
 function select(id:string){if(!course.some(e=>e.id===id))return;setSelectedId(id);setRevealed(false);const a=annotations[id];if(a&&side!=='both'&&!pointInSide(a.point,side))setSide(pointSide(a.point));}
 function changeRegion(r:Scope){setRegion(r);const first=course.find(e=>inScope(e,r));if(first)select(first.id);setQuery('');setIsolate(false);setPractice(false);camera(r==='skull-base'?'superior':'anterior');}
 function nextQuestion(){if(!landmarks.length){setNotice('This region has selectable bones. Choose another region to practice landmark recall.');return;}const alternatives=landmarks.filter(e=>e.id!==selectedId),pool=alternatives.length?alternatives:landmarks;select(pool[Math.floor(Math.random()*pool.length)].id);setPractice(true);setQuery('');setSide('both');camera('focus');}
 const filtered=entries.filter(e=>(e.label+' '+e.bone+' '+scopeLabels[e.region]).toLowerCase().includes(query.toLowerCase()));
 return <main><header className="masthead"><div className="brand"><Bone/><div><strong>Bone Atlas</strong><span>BIO 141 · Interactive anatomy</span></div></div><div className="header-actions"><span className="badge">Student edition</span><a className="credits-link" href="./credits.txt" target="_blank" rel="noreferrer">Model credits</a></div></header>
 <div className="workspace"><aside className="catalog"><p className="eyebrow">YOUR LAB BENCH</p><h1>Explore the skeleton.</h1><p className="muted">Select a structure or test your recall.</p><div className="region-switch">{(['all','axial','appendicular'] as Scope[]).map(r=><Button key={r} size="sm" onClick={()=>changeRegion(r)} aria-pressed={region===r} variant={region===r?'default':'outline'}>{r==='all'?'Whole':r==='axial'?'Axial':'Appendicular'}</Button>)}</div>
 <NativeSelect className="scope-select" aria-label="Skeleton region" value={region} onChange={e=>changeRegion(e.target.value as Scope)}>{Object.entries(scopeLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</NativeSelect>
 <div className="search-wrap"><Search size={15}/><Input aria-label="Search course structures" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a structure…" disabled={practice}/></div>
 <div className="list-heading"><p className="eyebrow">{scopeLabels[region]}</p><span>{entries.length} structures</span></div>
 {practice?<div className="practice-sidebar"><BookOpen/><h3>Recall practice</h3><p>Identify the highlighted landmark, then reveal its name.</p><p className="muted">Practice uses your instructor’s approved locations.</p><Button variant="outline" onClick={()=>setPractice(false)}>Return to structure list</Button></div>:<div className="structure-list">{filtered.map(e=><Button key={e.id} className={'structure-row '+(selectedId===e.id?'selected ':'')+(e.kind==='bone'?'bone-row':'')} variant="ghost" onClick={()=>select(e.id)} aria-pressed={selectedId===e.id}><span className="entry-icon">{e.kind==='bone'?<Bone size={15}/>:<Check size={14}/>}</span><span>{e.label}<small>{scopeLabels[e.region]}{e.kind==='landmark'?' · '+e.bone.replaceAll('-',' '):''}</small></span>{selectedId===e.id&&<ChevronRight size={14}/>}</Button>)}{!filtered.length&&<p className="muted">No structures match your search.</p>}</div>}
 <div className="catalog-footer"><span><Bone size={14}/> Bone or group</span><span><Check size={14}/> Approved landmark</span></div></aside>
 <section className="stage"><div className="stage-title"><span className="eyebrow">{scopeLabels[region]} · {side==='both'?'BOTH SIDES':side.toUpperCase()+' SIDE'}</span><h2>{hidden?'Name this landmark':selected.label}</h2><span className="stage-subtitle">{hidden?'Rotate the specimen to inspect the highlighted point.':selected.kind==='bone'?'Selected bone or bone group highlighted':annotation&&!pointInSide(annotation.point,side)?'Marker is on the other side · choose Both to see it':'Instructor-approved point marker'}</span></div>
 <Viewer region={region} side={side} selected={selected} annotations={annotations} isolate={isolate} showMarkers={showMarkers} practice={practice} placing={false} view={view} onSelect={id=>{if(!practice)select(id);}} onPlace={()=>{}} onNotice={setNotice}/>
 <div className="view-controls" aria-label="Camera presets">{(['anterior','posterior','superior','inferior','lateral'] as ViewName[]).map(v=><Button key={v} size="sm" variant="outline" onClick={()=>camera(v)}>{v[0].toUpperCase()+v.slice(1)}</Button>)}<Button size="icon" variant="outline" aria-label="Reset camera" onClick={()=>camera('reset')}><RotateCcw size={14}/></Button></div>
 <div className="stage-hint"><RotateCcw size={14}/> Drag / arrow keys to rotate · Pinch or + / − to zoom</div></section>
 <aside className="inspector"><div className="mode-tabs" aria-label="Learning mode"><Button size="sm" variant={!practice?'default':'ghost'} onClick={()=>setPractice(false)}><Eye/>Explore</Button><Button size="sm" variant={practice?'default':'ghost'} onClick={nextQuestion}><BookOpen/>Recall</Button></div>
 <p className="eyebrow">{practice?'RECALL PROMPT':'SELECTED STRUCTURE'}</p><h3 className="detail-title">{hidden?'What is this structure?':selected.label}</h3><p className="muted">{hidden?'Use its shape and position to identify the highlighted point.':selected.note}</p>
 {practice&&<div className="review-actions"><Button onClick={()=>setRevealed(true)} disabled={revealed}>Reveal name</Button><Button variant="outline" onClick={nextQuestion}>Next landmark</Button></div>}
 <div className="option-row"><label htmlFor="side">Anatomical side</label><NativeSelect id="side" size="sm" value={side} onChange={e=>setSide(e.target.value as Side)}><option value="both">Both</option><option value="right">Right</option><option value="left">Left</option></NativeSelect></div>
 <div className="option-row"><label htmlFor="isolate">Isolate selected structure</label><input id="isolate" type="checkbox" checked={isolate} onChange={e=>{setIsolate(e.target.checked);camera('focus');}}/></div>{!practice&&<div className="option-row"><label htmlFor="markers">Show other landmarks</label><input id="markers" type="checkbox" checked={showMarkers} onChange={e=>setShowMarkers(e.target.checked)}/></div>}
 <Button className="review-shortcut" variant="outline" onClick={()=>camera('focus')}><Target size={14}/>Focus on structure</Button>
 {!practice&&selected.region==='skull'&&region!=='skull-base'&&<Button className="review-shortcut" variant="outline" onClick={()=>changeRegion('skull-base')}>Open skull base</Button>}
 {!hidden&&<a className="reference-link" href={referenceUrl(selected.region)} target="_blank" rel="noreferrer">Open anatomy reference ↗</a>}
 <div className="prototype-note"><strong>Study with your course model</strong><p>The colored point locates a feature; it does not trace its full boundary. Each landmark uses one representative location.</p><p>Use Explore to study the bones and Recall to practice {landmarks.length} approved landmarks in this selection. Recall is ungraded and does not save scores.</p><a href="./credits.txt" target="_blank" rel="noreferrer">Anatomical model credits and license</a></div>
 </aside></div>{notice&&<div className="notice" role="status"><span>{notice}</span><Button variant="ghost" size="sm" aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</Button></div>}
 </main>;
}
